# Generated by Django 2.1.5 on 2019-02-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='photo',
        ),
    ]
